import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import { chromium, type Page } from "playwright";
import { adminPassword, freePort, magnetUrl, panUrl, projectRoot, startTestApi } from "./fixtures";

const api = await startTestApi();
const port = await freePort();
const web = spawn(process.execPath, [path.join(projectRoot, "node_modules/vite/bin/vite.js"), "--host", "127.0.0.1", "--port", String(port), "--strictPort"], {
  cwd: projectRoot, env: { ...process.env, API_ORIGIN: api.base }, windowsHide: true, stdio: "ignore"
});
const base = `http://127.0.0.1:${port}`;
const output = path.join(projectRoot, "artifacts/ui");
let browser: Awaited<ReturnType<typeof chromium.launch>> | undefined;
const errors: string[] = [];
async function checkOverflow(page: Page, label: string) {
  const overflow = await page.evaluate(() => document.documentElement.scrollWidth > window.innerWidth + 1);
  assert.equal(overflow, false, `${label}: page overflows the viewport`);
}
async function capture(page: Page, filename: string) {
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: path.join(output, filename), fullPage: true });
}
try {
  await mkdir(output, { recursive: true });
  for (let attempt = 0; attempt < 100; attempt++) {
    try { if ((await fetch(base)).ok) break; } catch { /* Wait for Vite. */ }
    await new Promise((resolve) => setTimeout(resolve, 100));
  }
  browser = await chromium.launch({ headless: true, ...(process.env.PLAYWRIGHT_CHANNEL ? { channel: process.env.PLAYWRIGHT_CHANNEL } : {}) });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, permissions: ["clipboard-read", "clipboard-write"] });
  const page = await context.newPage();
  page.on("pageerror", (error) => errors.push(error.message));
  page.on("dialog", (dialog) => dialog.accept());
  await page.goto(base);
  await page.locator(".media-card").first().waitFor();
  assert.equal(await page.getByPlaceholder("搜索影视名", { exact: true }).count(), 1);
  assert.equal(await page.locator(".nav-item").filter({ hasText: "VIP会员" }).count(), 0);
  assert.equal(await page.getByRole("button", { name: "后台管理" }).count(), 0);
  assert.equal(await page.locator("video").count(), 0);
  await capture(page, "home-desktop.png");
  assert.equal(await page.locator(".latest-category").count(), 4);
  assert.equal(await page.locator(".filters, .spotlight, .notice-board").count(), 0);
  assert.equal(await page.locator(".hot-carousel").count(), 0);
  const preview = await context.newPage();
  preview.on("pageerror", (error) => errors.push(error.message));
  const template = (await (await fetch(api.base + "/api/media")).json()).items[0];
  await preview.route("**/api/media", (route) => route.fulfill({ json: { items: ["电视剧", "电影", "综艺", "动漫"].flatMap((category) => Array.from({ length: 24 }, (_, index) => ({ ...template, id: `${category}-${index}`, title: `${category}测试${index + 1}`, category, updatedAt: new Date(Date.UTC(2026, 9, 1, index)).toISOString() }))) } }));
  await preview.goto(base);
  for (const width of [1440, 390]) {
    await preview.setViewportSize({ width, height: 1000 });
    await preview.waitForFunction(() => [...document.querySelectorAll(".latest-media-grid")].every((grid) => {
      const columns = getComputedStyle(grid).gridTemplateColumns.split(" ").length;
      return grid.children.length === columns * 2;
    }) && document.querySelectorAll(".latest-media-grid").length === 4);
    const positions = await preview.locator(".latest-media-grid").first().locator(".media-card").evaluateAll((cards) => cards.map((card) => Math.round(card.getBoundingClientRect().top)));
    assert.equal(new Set(positions).size, 2);
    await checkOverflow(preview, `latest homepage ${width}`);
    await capture(preview, `latest-home-${width}.png`);
  }
  await preview.close();
  const carouselContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const carousel = await carouselContext.newPage();
  carousel.on("pageerror", (error) => errors.push(error.message));
  const promotions = [
    { ...template, id: "hot-new", title: "正在热播新片", featured: true, updatedAt: "2026-10-09T08:00:00Z" },
    { ...template, id: "hot-old", title: "另一部热播电影", featured: true, updatedAt: "2026-10-08T08:00:00Z" },
    { ...template, id: "not-promoted", title: "未推送影视", featured: false }
  ];
  await carousel.route("**/api/media", (route) => route.fulfill({ json: { items: promotions } }));
  // A local bitmap keeps carousel layout checks independent of the image CDN.
  await carousel.goto(base);
  const landscape = await carousel.evaluate(() => {
    const canvas = document.createElement("canvas"); canvas.width = 1280; canvas.height = 720;
    const painter = canvas.getContext("2d")!;
    painter.fillStyle = "#567f75"; painter.fillRect(0, 0, 1280, 720);
    painter.fillStyle = "#b8cbd1"; painter.fillRect(850, 0, 430, 720);
    painter.fillStyle = "#efdbbb"; painter.fillRect(650, 140, 150, 480);
    return canvas.toDataURL("image/png");
  });
  promotions.forEach((film) => { film.backdropPath = landscape; });
  await carousel.reload();
  await carousel.getByRole("heading", { name: "正在热播新片", exact: true }).waitFor();
  assert.equal(await carousel.locator(".hot-pages button").count(), 2);
  assert.equal(await carousel.locator(".hot-backdrop").evaluate((image) => (image as HTMLImageElement).naturalWidth), 1280);
  assert.equal(await carousel.locator(".topbar").evaluate((element) => getComputedStyle(element).backgroundColor), await carousel.locator(".app-shell").evaluate((element) => getComputedStyle(element).backgroundColor));
  await carousel.getByRole("button", { name: "暂停自动轮播", exact: true }).click();
  await carousel.getByRole("button", { name: "下一部", exact: true }).click();
  await carousel.getByRole("heading", { name: "另一部热播电影", exact: true }).waitFor();
  await carousel.getByRole("button", { name: "上一部", exact: true }).click();
  await carousel.getByRole("heading", { name: "正在热播新片", exact: true }).waitFor();
  const menu = carousel.locator(".sidebar").getByRole("button", { name: "电影", exact: true });
  await menu.hover();
  await carousel.waitForFunction(() => getComputedStyle(document.querySelectorAll(".nav-item > span")[2]).transform !== "none");
  const bounds = await menu.boundingBox();
  await carousel.mouse.move(1200, 800);
  assert.deepEqual(await menu.boundingBox(), bounds, "menu emphasis must not move adjacent items");
  await capture(carousel, "hot-carousel-dark-desktop.png");
  await carousel.getByRole("button", { name: "切换浅色背景", exact: true }).click();
  await carousel.waitForFunction(() => document.documentElement.dataset.theme === "light");
  const lightText = await carousel.locator(".media-title").first().evaluate((element) => getComputedStyle(element).color);
  await carousel.reload();
  await carousel.getByRole("button", { name: "切换深色背景", exact: true }).waitFor();
  assert.equal(await carousel.evaluate(() => document.documentElement.dataset.theme), "light");
  await capture(carousel, "hot-carousel-light-desktop.png");
  await carousel.getByRole("button", { name: "切换深色背景", exact: true }).click();
  await carousel.waitForFunction(() => document.documentElement.dataset.theme === "dark");
  assert.notEqual(await carousel.locator(".media-title").first().evaluate((element) => getComputedStyle(element).color), lightText);
  await carousel.clock.install();
  await carousel.mouse.move(1400, 980);
  await carousel.getByPlaceholder("搜索影视名", { exact: true }).focus();
  await carousel.clock.fastForward(6700);
  await carousel.getByRole("heading", { name: "另一部热播电影", exact: true }).waitFor();
  await carousel.getByRole("button", { name: "暂停自动轮播", exact: true }).click();
  await carousel.clock.fastForward(20000);
  assert.equal(await carousel.locator(".hot-copy h1").textContent(), "另一部热播电影");
  await carousel.getByRole("button", { name: "展示正在热播新片", exact: true }).click();
  for (const width of [390, 320]) {
    await carousel.setViewportSize({ width, height: 844 });
    await checkOverflow(carousel, `hot carousel ${width}`);
    const action = await carousel.locator(".hot-detail").boundingBox();
    const controls = await carousel.locator(".hot-controls").boundingBox();
    assert.ok(action && controls && action.y + action.height <= controls.y, "carousel controls must not overlap film details");
    await carousel.getByRole("button", { name: "切换浅色背景", exact: true }).click();
    await carousel.getByRole("button", { name: "切换深色背景", exact: true }).waitFor();
    await capture(carousel, `hot-carousel-light-${width}.png`);
    await carousel.getByRole("button", { name: "切换深色背景", exact: true }).click();
    await carousel.getByRole("button", { name: "切换浅色背景", exact: true }).waitFor();
  }
  promotions[0].title = "特别长的热播电影名称以及电影系列最终章 ExtendedCinemaTitleWithoutSpaces";
  promotions[0].overview = "这是一段较长的影视简介，用来确认不同屏幕宽度下文字不会覆盖底部轮播控制按钮。".repeat(10);
  promotions[0].backdropPath = base + "/broken-hero.png";
  promotions[0].posterPath = landscape;
  await carousel.route("**/broken-hero.png", (route) => route.fulfill({ status: 404, body: "not found" }));
  await carousel.emulateMedia({ reducedMotion: "reduce" });
  await carousel.reload();
  await carousel.getByRole("button", { name: "开始自动轮播", exact: true }).waitFor();
  await carousel.waitForFunction(() => (document.querySelector(".hot-backdrop") as HTMLImageElement)?.naturalWidth === 1280);
  await carousel.clock.fastForward(20000);
  assert.equal(await carousel.locator(".hot-copy h1").textContent(), promotions[0].title);
  for (const width of [1440, 390, 320]) {
    await carousel.setViewportSize({ width, height: 844 });
    const action = await carousel.locator(".hot-detail").boundingBox();
    const controls = await carousel.locator(".hot-controls").boundingBox();
    assert.ok(action && controls && action.y + action.height <= controls.y, "long movie titles must not overlap carousel controls");
    await checkOverflow(carousel, `long carousel title ${width}`);
    await capture(carousel, `hot-carousel-long-title-${width}.png`);
  }
  await carousel.locator(".hot-detail").click();
  assert.ok(carousel.url().endsWith("/movie/hot-new"));
  assert.equal(await carousel.locator(".hot-carousel").count(), 0);
  await carousel.getByRole("button", { name: "切换浅色背景", exact: true }).click();
  await carousel.getByRole("button", { name: "切换深色背景", exact: true }).waitFor();
  await carousel.goto(base + "/admin");
  await carousel.getByRole("heading", { name: "管理员登录", exact: true }).waitFor();
  assert.equal(await carousel.evaluate(() => document.documentElement.dataset.theme), "dark");
  await carouselContext.close();
  await page.getByRole("region", { name: "电影最新更新", exact: true }).getByRole("button", { name: "更多", exact: true }).click();
  await page.getByLabel("年份筛选", { exact: true }).selectOption("2024");
  await page.getByLabel("评分筛选", { exact: true }).selectOption("8");
  await page.getByLabel("资源状态筛选", { exact: true }).selectOption("有资源");
  assert.equal(await page.locator(".media-card").count(), 1);
  await page.locator(".media-card").filter({ hasText: "验证电影" }).click();
  assert.ok(page.url().endsWith("/movie/test-movie"));
  await page.reload();
  await page.getByRole("heading", { name: "验证电影", exact: true }).waitFor();
  assert.match(await page.title(), /验证电影/);
  await page.getByRole("button", { name: "分享", exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), `${base}/movie/test-movie`);
  await page.goBack();
  await page.getByLabel("资源状态筛选", { exact: true }).waitFor();
  assert.equal(await page.getByLabel("资源状态筛选", { exact: true }).inputValue(), "有资源");
  await page.goForward();
  await page.getByRole("heading", { name: "验证电影", exact: true }).waitFor();
  assert.equal(await page.getByRole("tab").count(), 2);
  assert.equal(await page.locator(".resource-url-line").count(), 0);
  await page.goto(base + "/admin");
  await page.getByRole("heading", { name: "管理员登录" }).waitFor();
  await page.getByLabel("用户名", { exact: true }).fill("admin");
  await page.getByLabel("密码", { exact: true }).fill(adminPassword);
  await page.getByRole("button", { name: "登录后台" }).click();
  await page.getByRole("heading", { name: "媒体库", exact: true }).waitFor();
  await page.locator(".admin-table tbody tr").first().waitFor();
  await checkOverflow(page, "admin desktop");
  await capture(page, "admin-desktop.png");
  await page.getByRole("button", { name: "编辑验证电影", exact: true }).click();
  await page.getByRole("heading", { name: "编辑影视", exact: true }).waitFor();
  assert.equal(await page.getByLabel("115 网盘链接", { exact: true }).count(), 1);
  assert.equal(await page.getByLabel("磁力链接", { exact: true }).count(), 1);
  assert.equal(await page.getByText("AList", { exact: true }).count(), 0);
  await page.getByLabel("类型标签", { exact: true }).fill("动画");
  await page.getByLabel("首页热播推送", { exact: true }).check();
  await page.getByText("资源详情", { exact: true }).first().click();
  await page.getByLabel("115 网盘链接1分辨率", { exact: true }).selectOption("2160p / 4K");
  await page.getByLabel("115 网盘链接1动态范围", { exact: true }).selectOption("HDR10");
  await page.getByLabel("115 网盘链接1字幕", { exact: true }).fill("简体中文");
  await page.getByRole("button", { name: "保存影视", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "已保存" }).waitFor();
  assert.equal(await page.getByLabel("分类", { exact: true }).inputValue(), "动漫");
  await page.getByRole("button", { name: "站点设置", exact: true }).click();
  await page.getByLabel("注册提示文案", { exact: true }).fill("限时免费送7天体验会员，联系微信dkiss_zhou领取激活码。");
  await page.getByLabel("启用首页弹窗", { exact: true }).check();
  await page.getByLabel("公告标题", { exact: true }).fill("欢迎来到 Alum4K");
  await page.getByLabel("公告正文", { exact: true }).fill("这里是公告正文。\n管理员可以随时更新。<script>不会执行</script>");
  await page.getByRole("button", { name: "预览", exact: true }).click();
  await page.getByRole("dialog").waitFor();
  assert.equal(await page.locator(".announcement-content script").count(), 0);
  await page.getByRole("button", { name: "我知道了" }).click();
  await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
  await page.goto(base);
  await page.getByRole("dialog").waitFor();
  await capture(page, "announcement-desktop.png");
  await page.getByRole("button", { name: "我知道了" }).click();
  await page.reload();
  await page.locator(".media-card").first().waitFor();
  assert.equal(await page.getByRole("dialog").count(), 0);
  await page.locator(".hot-carousel").getByRole("heading", { name: "验证电影", exact: true }).waitFor();
  assert.equal(await page.locator(".hot-controls").count(), 0);
  await page.locator(".media-card").filter({ hasText: "验证电影" }).click();
  await page.locator(".resource-meta-quality").filter({ hasText: "2160p / 4K" }).waitFor();
  assert.equal(await page.locator(".resource-meta-size").textContent(), "18 GB");
  assert.match((await page.locator(".resource-meta-date").textContent()) || "", /^\d{4}-\d{2}-\d{2}$/);
  const linkRect = await page.locator(".resource-url-line").boundingBox();
  const metadataRect = await page.locator(".resource-metadata").boundingBox();
  assert.ok(linkRect && metadataRect && metadataRect.y >= linkRect.y + linkRect.height, "metadata must be below the link row");
  await page.getByRole("button", { name: "失效反馈", exact: true }).click();
  await page.getByLabel("反馈说明", { exact: true }).fill("请核验下载链接。");
  await page.getByRole("button", { name: "提交反馈", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "反馈已提交" }).waitFor();
  await page.getByRole("button", { name: "完成", exact: true }).click();
  await page.getByRole("button", { name: "复制链接", exact: true }).click();
  await page.getByRole("button", { name: "已复制链接", exact: true }).waitFor();
  assert.equal((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, "\n"), `${panUrl}\n提取码：abcd`);
  await page.getByRole("tab", { name: /磁力链接/ }).click();
  await page.getByRole("button", { name: "复制链接", exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), magnetUrl);
  assert.equal(await page.locator("video").count(), 0);
  await capture(page, "detail-desktop.png");
  await page.setViewportSize({ width: 390, height: 844 });
  await checkOverflow(page, "detail mobile");
  await capture(page, "detail-mobile.png");
  await page.goto(base + "/admin");
  await page.getByRole("heading", { name: "媒体库", exact: true }).waitFor();
  await page.getByRole("button", { name: "资源反馈", exact: true }).click();
  await page.getByText("请核验下载链接。", { exact: true }).waitFor();
  await checkOverflow(page, "resource reports mobile");
  await capture(page, "resource-reports-mobile.png");
  await page.getByRole("button", { name: "媒体库", exact: true }).click();
  await checkOverflow(page, "admin mobile");
  await capture(page, "admin-mobile.png");
  await page.getByRole("button", { name: "影视采集", exact: true }).click();
  await checkOverflow(page, "editor mobile");
  await capture(page, "editor-mobile.png");
  await page.getByRole("button", { name: "用户 / VIP", exact: true }).click();
  await checkOverflow(page, "users mobile");
  await page.getByRole("button", { name: "站点设置", exact: true }).click();
  await checkOverflow(page, "settings mobile");
  await capture(page, "settings-mobile.png");
  const logo = await page.evaluate(() => {
    const canvas = document.createElement("canvas"); canvas.width = 64; canvas.height = 64;
    const painter = canvas.getContext("2d")!;
    painter.fillStyle = "#197d75"; painter.fillRect(0, 0, 64, 64);
    painter.fillStyle = "#ffffff"; painter.font = "bold 44px sans-serif"; painter.fillText("A", 16, 48);
    return canvas.toDataURL("image/png");
  });
  await page.getByLabel("网站名称", { exact: true }).fill("Alum 4K 影视");
  await page.getByLabel("上传网站 Logo", { exact: true }).setInputFiles({ name: "logo.png", mimeType: "image/png", buffer: Buffer.from(logo.split(",")[1], "base64") });
  await page.locator(".logo-preview img").waitFor();
  await page.getByRole("radio", { name: "浅色", exact: true }).check();
  await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
  await page.waitForFunction(() => document.title === "Alum 4K 影视 · 管理后台" && document.documentElement.dataset.theme === "light");
  assert.equal(await page.locator('link[rel="icon"]').getAttribute("href"), logo);
  assert.equal(await page.locator(".brand-logo").evaluate((image) => (image as HTMLImageElement).naturalWidth), 64);
  await checkOverflow(page, "light settings mobile");
  await capture(page, "settings-light-mobile.png");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await capture(page, "settings-light-desktop.png");
  await page.getByRole("button", { name: "媒体库", exact: true }).click();
  await page.getByRole("button", { name: "编辑验证电影", exact: true }).click();
  await page.getByLabel("115 网盘链接", { exact: true }).fill(`电影分享：${panUrl} 提取码：newcode`);
  await page.getByLabel("115 网盘链接1查看权限", { exact: true }).selectOption("free");
  await page.getByLabel("磁力链接1查看权限", { exact: true }).selectOption("vip");
  await page.getByRole("button", { name: "保存影视", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "已保存" }).waitFor();
  assert.equal(await page.getByLabel("115 网盘链接", { exact: true }).inputValue(), `电影分享：${panUrl} 提取码：newcode`);
  assert.equal(await page.getByLabel("115 网盘链接1提取码", { exact: true }).inputValue(), "abcd");
  await capture(page, "editor-light-desktop.png");
  await page.getByLabel("115 网盘链接", { exact: true }).fill(panUrl);
  await page.getByRole("button", { name: "保存影视", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "已保存" }).waitFor();
  await page.getByRole("button", { name: "用户 / VIP", exact: true }).click();
  await page.getByRole("button", { name: "添加管理员", exact: true }).click();
  await page.getByLabel("管理员用户名", { exact: true }).fill("ui_admin");
  await page.getByLabel("管理员密码", { exact: true }).fill("ui-admin-password");
  await page.getByLabel("确认管理员密码", { exact: true }).fill("ui-admin-password");
  await page.getByRole("button", { name: "创建管理员", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "ui_admin 已添加" }).waitFor();
  assert.equal(await page.locator(".admin-user-row").filter({ hasText: "ui_admin" }).count(), 1);
  const guestContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const guest = await guestContext.newPage();
  guest.on("pageerror", (error) => errors.push(error.message));
  await guest.goto(base);
  await guest.getByRole("button", { name: "我知道了" }).click();
  await guest.waitForFunction(() => document.title === "Alum 4K 影视" && document.documentElement.dataset.theme === "light");
  await capture(guest, "home-light-mobile.png");
  await guest.locator(".media-card").filter({ hasText: "验证电影" }).click();
  await guest.getByRole("button", { name: "复制链接", exact: true }).waitFor();
  assert.equal(await guest.locator(".resource-url-line a").getAttribute("href"), panUrl);
  await checkOverflow(guest, "free download mobile");
  await capture(guest, "detail-light-mobile.png");
  await guest.getByRole("tab", { name: /磁力链接/ }).click();
  assert.equal(await guest.locator(".resource-url-line").count(), 0);
  assert.equal(await guest.locator(".locked-resource").count(), 1);
  await guest.goto(base + "/admin");
  await guest.getByLabel("用户名", { exact: true }).fill("ui_admin");
  await guest.getByLabel("密码", { exact: true }).fill("ui-admin-password");
  await guest.getByRole("button", { name: "登录后台", exact: true }).click();
  await guest.getByRole("heading", { name: "媒体库", exact: true }).waitFor();
  await guestContext.close();
  await page.getByRole("button", { name: "邀请码", exact: true }).click();
  await page.getByRole("button", { name: "生成邀请码", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "已生成" }).waitFor();
  const invitationCode = await page.locator(".invitation-table tbody code").first().innerText();
  assert.match(invitationCode, /^\d{8}$/);
  await page.getByRole("button", { name: `复制邀请码 ${invitationCode}`, exact: true }).click();
  assert.equal(await page.evaluate(() => navigator.clipboard.readText()), invitationCode);
  await capture(page, "invitations-desktop.png");
  await page.getByRole("button", { name: "站点设置", exact: true }).click();
  await page.getByLabel("前台浏览器标题", { exact: true }).fill("Alum4K 高清资源");
  await page.getByLabel("后台浏览器标题", { exact: true }).fill("Alum4K 运营后台");
  await page.getByLabel("网站介绍", { exact: true }).fill("影视资料和下载链接目录。");
  await page.getByRole("button", { name: "添加公告 / 广告", exact: true }).click();
  const bulletin = page.locator(".bulletin-edit-row").first();
  await bulletin.getByLabel("标题", { exact: true }).fill("新资源公告");
  await bulletin.getByLabel("正文", { exact: true }).fill("欢迎提交求片需求。<script>不会执行</script>");
  await page.getByRole("button", { name: "添加公告 / 广告", exact: true }).click();
  const advertisement = page.locator(".bulletin-edit-row").last();
  await advertisement.getByLabel("公告2类型", { exact: true }).selectOption("advertisement");
  await advertisement.getByLabel("标题", { exact: true }).fill("合作广告");
  await advertisement.getByLabel("正文", { exact: true }).fill("合作伙伴信息");
  await advertisement.getByLabel("跳转链接", { exact: true }).fill("https://example.com/");
  await advertisement.getByLabel("公告2图片", { exact: true }).setInputFiles({ name: "ad.png", mimeType: "image/png", buffer: Buffer.from(logo.split(",")[1], "base64") });
  await advertisement.locator(".bulletin-image-controls img").waitFor();
  await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
  await page.waitForFunction(() => document.title === "Alum4K 运营后台");
  assert.equal(await page.locator('meta[name="description"]').getAttribute("content"), "影视资料和下载链接目录。");
  assert.equal(await page.locator('meta[name="robots"]').getAttribute("content"), "noindex, nofollow");
  assert.equal(await page.getByRole("region", { name: "公告栏" }).count(), 1);
  const userContext = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const user = await userContext.newPage(); user.on("pageerror", (error) => errors.push(error.message));
  await user.goto(base);
  await user.getByRole("button", { name: "我知道了", exact: true }).click();
  await user.waitForFunction(() => document.title === "Alum4K 高清资源");
  assert.equal(await user.locator('link[rel="icon"]').getAttribute("href"), logo);
  assert.equal(await user.getByRole("region", { name: "公告栏" }).count(), 0);
  await user.getByRole("button", { name: "站点公告", exact: true }).click();
  await user.getByRole("dialog", { name: "公告栏", exact: true }).waitFor();
  assert.equal(await user.locator(".bulletin-list script").count(), 0);
  assert.equal(await user.locator(".bulletin-item").last().getByRole("link").getAttribute("rel"), "sponsored noreferrer");
  assert.equal(await user.locator(".bulletin-item img").evaluate((image) => (image as HTMLImageElement).naturalWidth), 64);
  await capture(user, "bulletins-desktop.png");
  await user.getByRole("button", { name: "关闭", exact: true }).click();
  await user.getByRole("button", { name: "求片", exact: true }).click();
  await user.getByRole("dialog", { name: "登录", exact: true }).waitFor();
  async function centered() {
    const rect = await user.getByRole("dialog").boundingBox(); const viewport = user.viewportSize()!;
    assert.ok(rect && Math.abs(rect.x + rect.width / 2 - viewport.width / 2) <= 2 && Math.abs(rect.y + rect.height / 2 - viewport.height / 2) <= 2, "login/register modal must be centered");
  }
  await centered(); await capture(user, "login-desktop.png");
  await user.setViewportSize({ width: 390, height: 400 }); await centered(); await checkOverflow(user, "short login viewport");
  await user.setViewportSize({ width: 390, height: 844 }); await centered();
  await capture(user, "login-mobile.png");
  await user.getByRole("button", { name: "没有账号？注册用户", exact: true }).click();
  await user.getByText("限时免费送7天体验会员，联系微信dkiss_zhou领取激活码。", { exact: true }).waitFor();
  await user.getByLabel("用户名", { exact: true }).fill("community_user");
  await user.getByLabel("密码", { exact: true }).fill("community-password");
  await user.getByLabel("邀请码", { exact: true }).fill(invitationCode);
  await centered(); await capture(user, "register-mobile.png");
  await user.getByRole("button", { name: "注册", exact: true }).click();
  await user.getByRole("button", { name: "个人信息", exact: true }).waitFor();
  await user.getByRole("dialog").getByRole("button", { name: "关闭", exact: true }).click();
  await user.getByRole("button", { name: "个人信息", exact: true }).click();
  await user.getByLabel("名称", { exact: true }).fill("影视爱好者");
  await user.getByLabel("个人介绍", { exact: true }).fill("喜欢电影和纪录片。");
  await user.getByLabel("上传头像", { exact: true }).setInputFiles({ name: "avatar.png", mimeType: "image/png", buffer: Buffer.from(logo.split(",")[1], "base64") });
  await user.locator(".profile-avatar img").waitFor();
  await user.getByRole("button", { name: "保存资料", exact: true }).click();
  await user.getByRole("status").filter({ hasText: "个人信息已保存" }).waitFor();
  assert.equal(await user.locator(".topbar-avatar").evaluate((image) => (image as HTMLImageElement).naturalWidth), 192);
  await checkOverflow(user, "profile mobile"); await capture(user, "profile-mobile.png");
  await user.getByRole("tab", { name: "修改密码", exact: true }).click();
  await user.getByLabel("当前密码", { exact: true }).fill("community-password");
  await user.getByLabel("新密码", { exact: true }).fill("community-new-password");
  await user.getByLabel("确认新密码", { exact: true }).fill("community-new-password");
  await user.getByRole("button", { name: "修改密码", exact: true }).click();
  await user.getByRole("status").filter({ hasText: "密码已修改" }).waitFor();
  await user.getByRole("button", { name: "关闭", exact: true }).click();
  await user.getByRole("button", { name: "求片", exact: true }).click();
  await user.getByLabel("影视名称", { exact: true }).fill("浏览器求片测试");
  await user.getByLabel("年份", { exact: true }).fill("2025");
  await user.getByLabel("需求说明", { exact: true }).fill("希望添加 4K 版本。");
  await user.getByRole("button", { name: "提交求片", exact: true }).click();
  await user.getByRole("status").filter({ hasText: "求片需求已提交" }).waitFor();
  await capture(user, "requests-mobile.png"); await checkOverflow(user, "requests mobile");
  await user.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: "求片管理", exact: true }).click();
  await page.getByLabel("浏览器求片测试处理状态", { exact: true }).selectOption("fulfilled");
  await page.getByLabel("浏览器求片测试管理员回复", { exact: true }).fill("已添加，欢迎查看。");
  await page.getByRole("button", { name: "保存处理", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "需求处理已保存" }).waitFor();
  await capture(page, "requests-admin-desktop.png");
  await user.getByRole("button", { name: "求片", exact: true }).click();
  await user.getByText("管理员回复：已添加，欢迎查看。", { exact: true }).waitFor();
  await user.getByRole("button", { name: "关闭", exact: true }).click();
  await page.getByRole("button", { name: "用户 / VIP", exact: true }).click();
  await page.locator(".admin-user-row").filter({ hasText: "community_user" }).getByRole("button", { name: "重置密码", exact: true }).click();
  await page.getByLabel("新密码", { exact: true }).fill("admin-reset-password");
  await page.getByLabel("确认新密码", { exact: true }).fill("admin-reset-password");
  await page.getByRole("button", { name: "确认重置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "密码已重置" }).waitFor();
  await user.getByRole("button", { name: "求片", exact: true }).click();
  await user.getByRole("dialog", { name: "登录", exact: true }).waitFor();
  await user.getByLabel("用户名", { exact: true }).fill("community_user");
  await user.getByLabel("密码", { exact: true }).fill("admin-reset-password");
  await user.getByRole("button", { name: "登录", exact: true }).click();
  await user.getByRole("button", { name: "个人信息", exact: true }).waitFor();
  await user.reload(); await user.getByRole("button", { name: "个人信息", exact: true }).waitFor();
  await user.getByRole("button", { name: "个人信息", exact: true }).click();
  assert.equal(await user.getByLabel("名称", { exact: true }).inputValue(), "影视爱好者");
  await user.getByRole("button", { name: "关闭", exact: true }).click();
  await user.getByRole("button", { name: "退出登录", exact: true }).click();
  await user.locator(".media-card").filter({ hasText: "验证电影" }).click();
  assert.equal(await user.locator(".resource-url-line a").getAttribute("href"), panUrl);
  await checkOverflow(user, "guest free link and notice board");
  await userContext.close();
  await page.getByRole("button", { name: "站点设置", exact: true }).click();
  for (const [name, theme] of [["深色", "dark"], ["石墨灰", "graphite"], ["森林绿", "forest"]]) {
    await page.getByRole("radio", { name, exact: true }).check();
    await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
    await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
    await page.waitForFunction((expected) => document.documentElement.dataset.theme === expected, theme);
    await checkOverflow(page, `${theme} desktop`);
    await capture(page, `settings-${theme}-desktop.png`);
  }
  await page.getByRole("button", { name: "媒体库", exact: true }).click();
  await page.getByRole("button", { name: "编辑验证电影", exact: true }).click();
  const rawText = "  任意分享内容\nhttps://example.com/download 提取码：Ab12  ";
  await page.getByLabel("首页热播推送", { exact: true }).uncheck();
  await page.getByLabel("115 网盘链接", { exact: true }).fill(rawText);
  await page.getByLabel("115 网盘链接1提取码", { exact: true }).fill("");
  await page.getByLabel("磁力链接", { exact: true }).fill("javascript:alert(1)");
  const auth = await (await fetch(api.base + "/api/auth/login", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ username: "admin", password: adminPassword }) })).json();
  const removed = await fetch(api.base + "/api/admin/media/test-movie", { method: "DELETE", headers: { authorization: `Bearer ${auth.token}` } });
  assert.equal(removed.status, 200);
  await page.getByRole("button", { name: "保存影视", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "已保存" }).waitFor();
  await page.goto(base);
  assert.equal(await page.locator(".hot-carousel").count(), 0);
  await page.locator(".media-card").filter({ hasText: "验证电影" }).click();
  assert.equal(await page.locator(".resource-plain-text").textContent(), rawText);
  assert.equal(await page.locator(".resource-url-line a").count(), 0);
  await page.getByRole("button", { name: "复制链接", exact: true }).click();
  assert.equal((await page.evaluate(() => navigator.clipboard.readText())).replace(/\r\n/g, "\n"), rawText);
  await page.getByRole("tab", { name: /磁力链接/ }).click();
  assert.equal(await page.locator(".resource-plain-text").textContent(), "javascript:alert(1)");
  assert.equal(await page.locator(".resource-open-button").count(), 0);
  await page.setViewportSize({ width: 390, height: 844 });
  await checkOverflow(page, "raw resource mobile");
  await capture(page, "raw-resource-mobile.png");
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(base + "/admin");
  await page.getByRole("button", { name: "站点设置", exact: true }).click();
  await page.getByLabel("注册需要邀请码", { exact: true }).uncheck();
  await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
  await page.getByLabel("注册需要邀请码", { exact: true }).scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(output, "registration-settings-desktop.png") });
  const memberContext = await browser.newContext({ viewport: { width: 390, height: 844 } });
  const member = await memberContext.newPage();
  member.on("pageerror", (error) => errors.push(error.message));
  await member.goto(base);
  await member.getByRole("button", { name: "我知道了", exact: true }).click();
  await member.getByRole("button", { name: "登录/注册", exact: true }).click();
  await member.getByRole("button", { name: "没有账号？注册用户", exact: true }).click();
  assert.equal(await member.getByLabel("邀请码", { exact: true }).count(), 0);
  await member.getByLabel("用户名", { exact: true }).fill("open_ui_member");
  await member.getByLabel("密码", { exact: true }).fill("test-member-password");
  await checkOverflow(member, "registration without invitation mobile");
  await capture(member, "register-without-invitation-mobile.png");
  const registrationResponse = member.waitForResponse((response) => response.url().endsWith("/api/auth/register") && response.request().method() === "POST");
  await member.getByRole("button", { name: "注册", exact: true }).click();
  const registered = await (await registrationResponse).json();
  assert.equal(registered.user.vip, true);
  assert.equal(registered.user.vipUntil, null);
  assert.equal(registered.user.role, "user");
  await member.getByRole("button", { name: "个人信息", exact: true }).waitFor();
  await member.locator(".media-card").filter({ hasText: "验证电影" }).click();
  await member.getByRole("tab", { name: /磁力链接/ }).click();
  await member.locator(".resource-plain-text").waitFor();
  assert.equal(await member.locator(".resource-plain-text").textContent(), "javascript:alert(1)");
  assert.equal(await member.locator(".locked-resource").count(), 0);
  await page.getByLabel("注册需要邀请码", { exact: true }).check();
  await page.getByRole("button", { name: "保存站点设置", exact: true }).click();
  await page.getByRole("status").filter({ hasText: "站点设置已保存" }).waitFor();
  await member.getByRole("button", { name: "退出登录", exact: true }).click();
  await member.goto(base);
  await member.getByRole("button", { name: "登录/注册", exact: true }).click();
  await member.getByRole("button", { name: "没有账号？注册用户", exact: true }).click();
  await member.getByLabel("邀请码", { exact: true }).waitFor();
  await memberContext.close();
  assert.deepEqual(errors, []);
  console.log("UI checks passed: hot carousel/push/rotation/pause, public theme toggle/persistence/admin isolation, stable menu emphasis, invitation policy toggle, automatic new-member VIP access, accounts/requests/bulletins/SEO, guest free links/VIP/copy and desktop/mobile layouts.");
  console.log(`Screenshots: ${output}`);
} catch (error) {
  console.error("Browser errors:", errors);
  const failedPage = browser?.contexts()[0]?.pages()[0];
  if (failedPage) { await capture(failedPage, "failure.png"); console.error((await failedPage.locator("body").innerText()).slice(0, 2000)); }
  throw error;
} finally {
  await browser?.close();
  if (web.exitCode === null) { const ended = new Promise<void>((resolve) => web.once("exit", () => resolve())); web.kill(); await ended; }
  await api.close();
}
